name: Infracost Cost Diff

on:
  pull_request:            # run on every PR
    types: [opened, synchronize, reopened]

jobs:
  infracost:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Terraform (if your repo doesn’t already do this)
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      # Install Infracost
      - name: Install Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      # Generate cost JSON for the base and head commits
      - name: Infracost diff
        run: |
          infracost diff \
            --path=. \
            --format github-comment \
            --out-file=/tmp/infracost-comment.json

      # Post or update the PR comment
      - name: Post cost comment
        uses: infracost/actions/comment@v3
        with:
          path: /tmp/infracost-comment.json
