name: Infracost Cost Diff

on:
  pull_request:            # run on every PR
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read

jobs:
  infracost:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Terraform (if your repo doesn’t already do this)
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      # Install Infracost
      - name: Install Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

    #   - name: Generate baseline cost estimate
    #     run: infracost breakdown --path . --format json --out-file infracost-base.json

      - name: Generate Infracost base breakdown
        run: infracost breakdown --path . --format json --out-file infracost-base.json
        env:
          INFRACOST_SKIP_CLOUD: true

      - name: Run Infracost diff
        run: infracost diff --path . --compare-to infracost-base.json --format json --out-file /tmp/infracost-diff.json
        env:
          INFRACOST_SKIP_CLOUD: true

      # Post or update the PR comment
      - name: Post cost comment
        uses: infracost/actions/comment@v1
        with:
          path: /tmp/infracost-diff.json
          behavior: update
        env:
          INFRACOST_SKIP_CLOUD: true
